version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: "@blackflux/robo-config-plugin"
    versions:
    - 4.1.3
  - dependency-name: chai
    versions:
    - 4.3.2
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
  - dependency-name: object-scan
    versions:
    - 13.9.3
  - dependency-name: babel-preset-latest-node
    versions:
    - 5.5.0
  - dependency-name: object-hash-strict
    versions:
    - 2.0.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
